/**
 * Utility to generate HTML for the PDF Itinerary
 */
function generateItineraryHTML(itinerary, city = "Your Trip") {
    const daysHtml = itinerary.days.map(day => {
        const activitiesHtml = day.activities.map(act => `
            <div style="margin-bottom: 15px; border-left: 2px solid #3b82f6; padding-left: 15px;">
                <div style="font-weight: bold; color: #1e293b;">${act.time} - ${act.activity}</div>
                <div style="font-size: 0.9em; color: #64748b;">📍 ${act.location}</div>
                ${act.notes ? `<div style="font-size: 0.85em; color: #475569; font-style: italic; margin-top: 5px;">${act.notes}</div>` : ''}
            </div>
        `).join('');

        return `
            <div style="margin-bottom: 30px; background: #f8fafc; padding: 20px; border-radius: 10px;">
                <h2 style="color: #2563eb; margin-top: 0;">Day ${day.day}</h2>
                ${activitiesHtml}
            </div>
        `;
    }).join('');

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: 'Helvetica', sans-serif; line-height: 1.6; color: #334155; max-width: 800px; margin: 40px auto; padding: 20px; }
            h1 { text-align: center; color: #1e3a8a; font-size: 2.5em; margin-bottom: 10px; }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; }
            .footer { text-align: center; margin-top: 40px; font-size: 0.8em; color: #94a3b8; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>TripGPT Itinerary</h1>
            <p>Your custom plan for <strong>${city}</strong></p>
        </div>
        
        ${daysHtml}

        <div class="footer">
            <p>Generated by Antigravity Travel AI</p>
            <p>Data sourced from OpenStreetMap & Wikivoyage</p>
        </div>
    </body>
    </html>
    `;
}

module.exports = { generateItineraryHTML };
